// -> IT IS USED TO MAKE COMMENTS
// -> É USADO PARA REALIZAR COMENTÁRIOS

/*
    THIS IS USED TO ASSEMBLE 
    COMMENT BLOCKS WITH
    MULTIPLE LINES
    
    ESSE É USADO PARA MONTAR 
    BLOCOS DE COMENTÁRIOS COM
    VÁRIAS LINHAS
 */

// CODE USED FOR DISPLAY (SIMMAR AS PRINT CODE)
// CÓDIGO USADO PARA EXIBIÇÃO (PARECIDO COM O CÓDIGO PRINT)
console.log("Test");

// CODE BLOCK
// BLOCO DE CÓDIGO
{
	console.log("Demo");
}
